# Generated by ./update.sh - do not update manually!
# Last updated: 2023-12-24
{
  compatList = {
    rev = "04f976dd3b90ca38ef02751ae53fd1f1e36b44d0";
    hash = "sha256:1b0g1i6bx89syqi87ia4fmmc22mndg6skpr759rayq5hsqlvcb9q";
  };

  mainline = {
    version = "1661";
    hash = "sha256:047kdrrj2sdd8349xldqhcxqdz267l8hmpimr3qxy2nlgsc1c2ly";
  };

  ea = {
    version = "4033";
    distHash = "sha256:1sxn9lsvbdaagfz7cdsdv4c7dlzf28v73g8d7wa13j23lj6f2ncp";
    fullHash = "sha256:0k7l6gl75axmbbvnh1hi58qs349pwiv5fygsvjbqnli1zynqmb7h";
  };
}
